version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  test-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - "5434:5432"
    expose:
      - "5434"
    volumes:
      - test-db-data:/var/lib/postgresql/data:cached

  api:
    build: .
    command: bash -c "alembic upgrade head && uvicorn source_code.app:app --host 0.0.0.0 --reload"
    volumes:
      - .:/code
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql+asyncpg://dev-user:password@postgres:5432/dev_db"
    ports:
      - "8008:8000"
    depends_on:
      - postgres
      - rabbitmq

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    logging:
      driver: none

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672" # rabbitmq
      - "15672:15672" # management interface
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
        - app_network

volumes:
  db-data:
  test-db-data:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge